name: Java CI with Maven
run-name: Build & Test Java 17 Project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
name: Checkout repository
      uses: actions/checkout@v4

      
name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'

      
name: Build and test with Maven
      run: mvn -B clean verify
